"use client";
import { useEffect, useState } from "react";
import { Breadcrumbs } from "../breadcrumbs";
import { SafeLink as Link } from "../safe-link";
import { ThemeToggle } from "../pwa";
import { currentAccessToken, currentOnlineUser, signInOnline, signOutOnline, supabaseConfigured, updateDeveloperPassword } from "../lib/supabase";

type Environment="test"|"production";
type Summary={activeEnvironment:Environment;test:Record<string,string|boolean>;production:Record<string,string|boolean>};
type Prices={environment:Environment;monthlyPrice:number;annualPrice:number;monthlyPlanConfigured:boolean;annualPlanConfigured:boolean};
const empty={publicKey:"",accessToken:"",clientId:"",clientSecret:"",webhookSecret:""};
async function api(path:string,method="GET",body?:unknown){const token=await currentAccessToken();if(!token)throw new Error("Entre com a conta autorizada.");const response=await fetch(path,{method,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||"Não foi possível acessar o painel.");return data}

export default function DeveloperClient(){
 const [ready,setReady]=useState(false),[authorized,setAuthorized]=useState(false),[mustChange,setMustChange]=useState(false),[email,setEmail]=useState("dansouzafloripa@gmail.com"),[password,setPassword]=useState(""),[visible,setVisible]=useState(false),[newPassword,setNewPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState(""),[summary,setSummary]=useState<Summary|null>(null),[environment,setEnvironment]=useState<Environment>("test"),[form,setForm]=useState(empty),[makeActive,setMakeActive]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [prices,setPrices]=useState<Prices|null>(null),[monthlyPrice,setMonthlyPrice]=useState(49.9),[annualPrice,setAnnualPrice]=useState(478.8);
 const load=async()=>{const [credentials,planData]=await Promise.all([api("/api/developer/mercado-pago") as Promise<Summary>,api("/api/developer/plans") as Promise<Prices>]);setSummary(credentials);setEnvironment(credentials.activeEnvironment);setPrices(planData);setMonthlyPrice(planData.monthlyPrice);setAnnualPrice(planData.annualPrice);setAuthorized(true)};
 useEffect(()=>{(async()=>{try{const user=await currentOnlineUser();if(user?.email?.toLowerCase()==="dansouzafloripa@gmail.com"){if(user.user_metadata?.force_password_change===true)setMustChange(true);else await load()}}catch{setAuthorized(false)}finally{setReady(true)}})()},[]);
 const login=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try{await signInOnline(email,password);const user=await currentOnlineUser();if(user?.email?.toLowerCase()!=="dansouzafloripa@gmail.com"){await signOutOnline();throw new Error("Acesso permitido somente à conta autorizada.")}if(user.user_metadata?.force_password_change===true)setMustChange(true);else await load()}catch(err){setMessage(err instanceof Error?err.message:"Acesso negado.")}finally{setBusy(false)}};
 const changePassword=async(e:React.FormEvent)=>{e.preventDefault();setMessage("");if(newPassword.length<12){setMessage("Use uma senha com pelo menos 12 caracteres.");return}if(newPassword!==confirmPassword){setMessage("As senhas não coincidem.");return}setBusy(true);try{await updateDeveloperPassword(newPassword);setNewPassword("");setConfirmPassword("");setMustChange(false);await load();setMessage("Senha definida com segurança.")}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível definir a senha.")}finally{setBusy(false)}};
 const saveCredentials=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try{await api("/api/developer/mercado-pago","POST",{environment,...form,makeActive});setForm(empty);await load();setMessage("Credenciais validadas e salvas com segurança.")}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível salvar.")}finally{setBusy(false)}};
 const savePrices=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try{await api("/api/developer/plans","POST",{environment,monthlyPrice,annualPrice});await load();setMessage("Valores salvos e planos sincronizados com o Mercado Pago.")}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível atualizar os planos.")}finally{setBusy(false)}};
 if(!ready)return <Shell><p className="mt-16 text-center">Verificando acesso…</p></Shell>;
 if(!supabaseConfigured)return <Shell><Notice text="Configure o Supabase para ativar a autenticação exclusiva e o cofre de credenciais."/></Shell>;
 if(mustChange)return <Shell><main className="mx-auto mt-16 max-w-md rounded-3xl border border-[#29443a] bg-[#10211b] p-7 shadow-2xl"><p className="eyebrow">Primeiro acesso</p><h1 className="mt-2 text-3xl font-extrabold">Defina sua nova senha</h1><p className="mt-3 text-sm text-[#a7bbb3]">Por segurança, substitua a senha temporária antes de abrir o painel.</p><form className="mt-7 space-y-4" onSubmit={changePassword}><label className="label">Nova senha<input className="input" type="password" minLength={12} value={newPassword} onChange={e=>setNewPassword(e.target.value)} autoComplete="new-password" required/></label><label className="label">Confirmar nova senha<input className="input" type="password" minLength={12} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} autoComplete="new-password" required/></label>{message&&<p className="rounded-xl bg-red-950/40 p-3 text-sm text-red-200">{message}</p>}<button className="btn btn-primary w-full" disabled={busy}>{busy?"Salvando…":"Definir senha e continuar"}</button></form></main></Shell>;
 if(!authorized)return <Shell><main className="mx-auto mt-16 max-w-md rounded-3xl border border-[#29443a] bg-[#10211b] p-7 shadow-2xl"><p className="eyebrow">Acesso restrito</p><h1 className="mt-2 text-3xl font-extrabold">Painel do desenvolvedor</h1><p className="mt-3 text-sm text-[#a7bbb3]">Somente a conta autorizada pode entrar.</p><form className="mt-7 space-y-4" onSubmit={login}><label className="label">E-mail<input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label className="label">Senha<div className="relative"><input className="input pr-12" type={visible?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} required/><button type="button" className="absolute right-2 top-2 h-9 w-9" onClick={()=>setVisible(!visible)} aria-label={visible?"Ocultar senha":"Mostrar senha"}>👁</button></div></label>{message&&<p className="rounded-xl bg-red-950/40 p-3 text-sm text-red-200">{message}</p>}<button className="btn btn-primary w-full" disabled={busy}>{busy?"Verificando…":"Entrar no painel"}</button></form></main></Shell>;
 const current=summary?.[environment]||{};
 return <Shell><main className="mt-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Integrações privadas</p><h1 className="title mt-2">Mercado Pago</h1><p className="mt-2 text-sm text-[#a7bbb3]">Gerencie credenciais e preços sem expor valores secretos.</p></div><button className="btn btn-secondary" onClick={async()=>{await signOutOnline();setAuthorized(false);setMustChange(false)}}>Sair</button></div>
 <div className="mt-7 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><section className="card p-6"><h2 className="text-lg font-extrabold">Ambientes</h2><div className="mt-5 grid gap-3">{(["test","production"] as Environment[]).map(item=>{const info=summary?.[item];return <button key={item} onClick={async()=>{setEnvironment(item);setForm(empty);setMakeActive(false);const selected=await api(`/api/developer/plans?environment=${item}`) as Prices;setPrices(selected);setMonthlyPrice(selected.monthlyPrice);setAnnualPrice(selected.annualPrice)}} className={`rounded-2xl border p-4 text-left ${environment===item?"border-[#65b6a1] bg-[#17352b]":"border-[#29443a]"}`}><div className="flex justify-between"><b>{item==="test"?"Teste":"Produção"}</b>{summary?.activeEnvironment===item&&<span className="status confirmado">Ativo</span>}</div><p className="mt-2 text-xs text-[#91a79f]">{info?.configured?"Credenciais configuradas":"Aguardando configuração"}</p></button>})}</div><div className="mt-6 space-y-2 text-xs text-[#91a79f]"><p>Public Key: {String(current.publicKey||"")}</p><p>Access Token: {String(current.accessToken||"")}</p><p>Client ID: {String(current.clientId||"")}</p><p>Client Secret: {String(current.clientSecret||"")}</p><p>Webhook: {String(current.webhookSecret||"")}</p></div></section>
 <section className="card p-6"><h2 className="text-lg font-extrabold">Atualizar ambiente de {environment==="test"?"teste":"produção"}</h2><p className="mt-2 text-xs text-[#91a79f]">Campos vazios mantêm o valor atual.</p><form className="mt-6 grid gap-4" onSubmit={saveCredentials}><Field label="Public Key" value={form.publicKey} set={v=>setForm({...form,publicKey:v})}/><Field label="Access Token" secret value={form.accessToken} set={v=>setForm({...form,accessToken:v})}/><Field label="Client ID" value={form.clientId} set={v=>setForm({...form,clientId:v})}/><Field label="Client Secret" secret value={form.clientSecret} set={v=>setForm({...form,clientSecret:v})}/><Field label="Chave secreta do webhook" secret value={form.webhookSecret} set={v=>setForm({...form,webhookSecret:v})}/><label className="flex items-center gap-3 rounded-xl border border-[#29443a] p-4 text-sm font-bold"><input type="checkbox" checked={makeActive} onChange={e=>setMakeActive(e.target.checked)}/> Tornar este o ambiente ativo após salvar</label><button className="btn btn-primary" disabled={busy}>{busy?"Validando…":"Validar e salvar"}</button></form></section></div>
 <section className="card mt-6 p-6"><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><p className="eyebrow">Preços da assinatura</p><h2 className="mt-1 text-xl font-extrabold">Planos mensal e anual</h2></div><span className="status confirmado self-start">Ambiente: {environment==="test"?"teste":"produção"}</span></div><form className="mt-6 grid gap-4 md:grid-cols-2" onSubmit={savePrices}><label className="label">Plano mensal (R$)<input className="input" type="number" min="1" step="0.01" value={monthlyPrice} onChange={e=>setMonthlyPrice(Number(e.target.value))} required/></label><label className="label">Plano anual (R$)<input className="input" type="number" min="1" step="0.01" value={annualPrice} onChange={e=>setAnnualPrice(Number(e.target.value))} required/></label><div className="rounded-xl bg-[#152b23] p-4 text-xs text-[#a7bbb3] md:col-span-2"><p>Plano mensal no MP: {prices?.monthlyPlanConfigured?"configurado":"será criado"}</p><p className="mt-1">Plano anual no MP: {prices?.annualPlanConfigured?"configurado":"será criado"}</p><p className="mt-2">Os novos valores valem para novas assinaturas. Assinaturas existentes não são reajustadas automaticamente.</p></div><button className="btn btn-primary md:col-span-2" disabled={busy}>{busy?"Sincronizando…":"Salvar valores e atualizar Mercado Pago"}</button></form></section>{message&&<p className="mt-5 rounded-xl bg-[#17352b] p-3 text-sm text-[#a9ddcf]">{message}</p>}</main></Shell>;
}
function Field({label,value,set,secret=false}:{label:string;value:string;set:(v:string)=>void;secret?:boolean}){return <label className="label">{label}<input className="input" type={secret?"password":"text"} value={value} onChange={e=>set(e.target.value)} autoComplete="off"/></label>}
function Shell({children}:{children:React.ReactNode}){return <div className="developer-shell system-theme min-h-screen bg-[#08140f] px-4 py-6 text-[#e8f3ef]"><div className="mx-auto max-w-5xl"><header className="flex items-center justify-between"><Link href="/" className="font-extrabold">✦ Agenda Profissa</Link><ThemeToggle compact/></header><Breadcrumbs items={[{label:"Início",href:"/"},{label:"Painel do desenvolvedor"}]} className="mt-8"/>{children}</div></div>}
function Notice({text}:{text:string}){return <div className="mx-auto mt-16 max-w-xl rounded-2xl border border-amber-800/50 bg-amber-950/20 p-6 text-center"><h1 className="text-xl font-extrabold">Painel preparado</h1><p className="mt-3 text-sm text-amber-100">{text}</p></div>}
